### ISSUE TITLE
Removed from Mozilla Addon site

### ISSUE THREAD

**Issue by yusf** [Noitidart/Chrome-Store-Foxified#10]
It's [gone](https://addons.mozilla.org/en-us/firefox/addon/chrome-store-foxified/). 💢

**Comment by Noitidart** [comment]
Thanks much @yusf - it got removed because we toggled the xpi.signatures.required preference to false. I'm getting permission for that pref to work in 43 and 44, and then Fx 45+ I'll switch to loading temporary addons - https://blog.mozilla.org/addons/2015/12/23/loading-temporary-add-ons/

**Comment by yusf** [comment]
Thought it could be that, but considered browser politica also for a moment.

And thanks, being a graphic designer and comic book lover has to show through sometimes.

**Comment by Noitidart** [comment]
Thanks @yusf! - I just released v1.3 which fixes this - https://github.com/Noitidart/Chrome-Store-Foxified/releases/tag/v1.3

The upload to AMO is going slow right now, I'll link that as soon as its complete.

**Comment by Noitidart** [comment]
I'ts up - https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/ - thanks again!

**Comment by yusf** [comment]
Still gone by the looks of it.

**Comment by Noitidart** [comment]
Thanks for that check up! It got rejected last night, it was understandable. What happened was, because Firefox 43 and 44 don't yet support loading temporary addons (thus still support the pref), I left in that pref change. But I wasn't requesting user permission for togging that pref, so it got rejected. Fixed that and release v1.4 :)

**Comment by Noitidart** [comment]
Reopneing for now, I wasn't able to get it through the review process.

I have another idea and will try that out :)

**Comment by yusf** [comment]
But isn't temporary addons loading suppose to be a developer's test tool only? As i understand it, users need to temporary load the addon on each boot which is not great permanent UX.

**Comment by Noitidart** [comment]
Yep @yusf that's why for this next version I am using the AMO api and signing the addons. But I add in `-foxified` to the id, so in case the dev wants to make an actual firefox version, the id they expect is still available (meaning I don't steal it). This is the topic where I work it out - https://github.com/mozilla/olympia/issues/1369

**Comment by yusf** [comment]
Interesting

**Comment by Noitidart** [comment]
Hey @yusf just uploaded the version to support signing. :) 

v1.5 -

* https://github.com/Noitidart/Chrome-Store-Foxified/releases/tag/v1.5
* https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/

**Comment by Noitidart** [comment]
v1.7 fixes the signing issue, it was a bug on my part -

https://github.com/Noitidart/Chrome-Store-Foxified/releases/tag/v1.7

Uploaded to AMO :)

Please close after verification :)

**Comment by yusf** [comment]
Looks good! :+1:

**Comment by yusf** [comment]
Sorry, no good! Am prevented from installing "unverified" addon.

**Comment by Noitidart** [comment]
Ah let me see if I can get some friends on the review team to take a look :)

**Comment by Noitidart** [comment]
Hey @yusf I got preliminary approval, please test :)

**Comment by yusf** [comment]
Works now. (FF DE 46.0a2)

**Comment by Noitidart** [comment]
Thanks very much! :)

**Comment by yusf** [comment]
Good work. Thanks!
