### ISSUE TITLE
google hangout extension does nothing

### ISSUE THREAD

**Issue by kahing** [Noitidart/Chrome-Store-Foxified#15]
https://chrome.google.com/webstore/detail/google-hangouts/

probably because it needs a google account and never asked me for one

**Comment by Noitidart** [comment]
Looks like the addon is installing fine for me. Did it not install for you?

**Comment by kahing** [comment]
It installed but clicking the button does nothing
On Apr 4, 2016 20:09, Noitidart <notifications@github.com> wrote:Looks like the addon is installing fine for me. Did it not install for you?

**Comment by kahing** [comment]
are these kind of bug reports helpful? Actually I've tried a few different extensions and none of them worked for me. Could content processes be related as well?

**Comment by Noitidart** [comment]
I'll take a deeper look into it. Usually though it is due to the extensions using APIs not yet landed to the WebExtension API. So it can't be the content process, as when the Moz team adds support they handle the content process stuff for us. :) I'll look into this addon in more detail and let you know though. I appreciate the question! :)
