### ISSUE TITLE
cannot close "XXX" was successfuly installed notification

### ISSUE THREAD

**Issue by kahing** [Noitidart/Chrome-Store-Foxified#17]
![extension-installed](https://cloud.githubusercontent.com/assets/1772540/14260220/4fa96682-fa5f-11e5-8bb7-e45f99eda7b9.png)

**Comment by Noitidart** [comment]
Very interesting. Clicking the "x" button at far right is not closing the bar?

**Comment by kahing** [comment]
Didn't do anything for me. Could it be related to tree style tabs? 
On Apr 4, 2016 20:07, Noitidart <notifications@github.com> wrote:Very interesting. Clicking the "x" button at far right is not closing the bar?

**Comment by Zaggy1024** [comment]
I believe this happens only in tabs with the content separate from the chrome, because if I click the close button in an "about:" page or a non-e10s window, it works. Otherwise, clicking the close button or any other buttons (such as the button to view the signing response json) on those bars doesn't work.

**Comment by Noitidart** [comment]
Thats a very interesting observation, thanks @Zaggy1024 !

**Comment by Noitidart** [comment]
Fixed in v1.10 just uploaded it to AMO. It was an e10s issue I was not handling properly on my side. Thanks for @Zaggy1024 test case that helped fix it. :)
