### ISSUE TITLE
Provide an option to remove signing process

### ISSUE THREAD

**Issue by vyvl** [Noitidart/Chrome-Store-Foxified#19]
I think signing is only necessary for who require xpi signatures. So if you could provide an option where we can skip signing it will help us when we face signing error at the store. Also provide a way to add addons manually by selecting a .crx file.

**Comment by Noitidart** [comment]
This is a good idea. I'll add these options.

With Firefox 46 though they removed the signatures required pref though, so if you want to install it has to be signed no?

**Comment by vyvl** [comment]
I am on nightly channel, it still has that pref. So it is useful for people using other firefox builds or variants.

**Comment by Juesto** [comment]
signature verification pref still exists as of 46.

**Comment by Noitidart** [comment]
AMO reviewers don't allow respecting that pref as it is sure fire for deprecation. So I did add a do-not sign pref though. This installs it as a temporary addon. The xpi is also on the desktop, or whatever directory you tell it to save in. So you can just drag that xpi.

But I can't get it onto AMO otherwise :(

**Comment by Noitidart** [comment]
Just uploaded v1.10 - there is an option for "Do not sign", and it will load it as a temporary addon. @vyvl is this acceptable?

**Comment by vyvl** [comment]
Thanks for the feature, I am closing this issue now.

**Comment by Noitidart** [comment]
Awesome thanks again! It was a great idea :)
